### ISSUE TITLE
does the detect-branch works

### ISSUE THREAD

**Issue by adamas-v** [asrafulashiq/doagan_clean#7]
Hi , thx for your great job ,but i test the model with your trained params and the output of detect branch is always greater than 10,
i have test with forgery sample and pristine samples 
can you help me out

**Comment by asrafulashiq** [comment]
The detection branch works only for USC-ISI dataset, not for the external datasets (CASIA, CoMo, etc.). To detect image-level forgery, we predict an image to contain forgery whenever there are more than 200 forged pixels in the output mask. 

Hope it helps.

**Comment by adamas-v** [comment]
Get it. thanks
